name: 'Check Branch Name'
description: 'check the name convention of the branch'
runs:
  using: "composite"
  steps:
    - run: |
        echo "1 $GITHUB_REF" 
        echo "2 $GITHUB_BASE_REF"
        echo "3  $GITHUB_HEAD_REF"
        if ! [[ "$(echo ${GITHUB_HEAD_REF} | cut -d "/" -f1)" =~ (feature|hotfix|bugfix|release) ]]; then
          exit 1
        elif [[ "$(echo ${GITHUB_HEAD_REF} | cut -d "/" -f1)" == "hotfix" && ! "$(echo ${GITHUB_BASE_REF})" =~ (master|main) ]]; then
          exit 1
        elif [[ "$(echo ${GITHUB_HEAD_REF} | cut -d "/" -f1)" =~ (feature|hotfix|bugfix) && ! "$(echo ${GITHUB_HEAD_REF} | cut -d "/" -f1)" =~ '[A-Z]+-[0-9]+' ]]; then
          exit 1
        fi 
      shell: bash